# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MpdRichPresence < Formula
  desc "MPD Rich Presence for Discord"
  homepage "https://winston.sh"
  version "0.7.0"

  depends_on "mpd"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nekowinston/mpd-rich-presence/releases/download/v0.7.0/mpd-rich-presence_0.7.0_darwin_arm64.tar.gz"
      sha256 "73b92597f78d72a5fa7f7ff5bd5d0be8d59a981abb26b74e4c20c18a266f0a01"

      def install
        bin.install "mpd-rich-presence"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nekowinston/mpd-rich-presence/releases/download/v0.7.0/mpd-rich-presence_0.7.0_darwin_amd64.tar.gz"
      sha256 "a15156e88bc8e6a142f60b1a87164d1104b203959fb2538069fc09dd62f95640"

      def install
        bin.install "mpd-rich-presence"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nekowinston/mpd-rich-presence/releases/download/v0.7.0/mpd-rich-presence_0.7.0_linux_arm64.tar.gz"
      sha256 "68cc3c8ea4b814b60958abbfaa0b05f7f7bbe0dee1d6fa201a6088f8e8c11251"

      def install
        bin.install "mpd-rich-presence"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nekowinston/mpd-rich-presence/releases/download/v0.7.0/mpd-rich-presence_0.7.0_linux_amd64.tar.gz"
      sha256 "72fba0ddbd07cf0531a7b7e671b97d316cdfb9e2838d8da79ffdf8feffc18698"

      def install
        bin.install "mpd-rich-presence"
      end
    end
  end

  service do
    run [opt_bin/"mpd-rich-presence"]
    keep_alive true
    log_path var/"log/mpd-rich-presence.log"
    error_log_path var/"log/mpd-rich-presence.log"
  end
end
